routes/web.php
<?php

use App\Http\Controllers\ActividadManoObraController;
use App\Http\Controllers\ArchivosSolicitudController;
use App\Http\Controllers\CronogramaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\inicioControl;
use App\Http\Controllers\SolicitudController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\InformeController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\Materials_informesController;
use App\Http\Controllers\DescargoController;
use App\Http\Controllers\EjecucionController;
use App\Http\Controllers\Mano_ObrasController;
use App\Http\Controllers\MonitorController;
use App\Http\Controllers\PDFController;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

Route::get('/', inicioControl::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('dash.index');
})->name('dash');
// CRUD USUARIOS
Route::resource('users', UserController::class)->only('index', 'edit', 'update', 'create', 'store')->names('users');
// Crud SOLICITUD
Route::get('Lista_solicitud', [SolicitudController::class, 'index'])->middleware('can:solicitud.index')->name('solicitud.index');
Route::get('solicitud/registrar_solicitud', [SolicitudController::class, 'create'])->middleware('can:solicitud.create')->name('solicitud.create');
Route::post('solicitud/registrar_solicitud', [SolicitudController::class, 'store'])->name('solicitud.store');
Route::get('solicitud/{solicitud}/edit', [SolicitudController::class, 'edit'])->middleware('can:solicitud.edit')->name('solicitud.edit');
Route::put('solicitud/{solicitud}', [SolicitudController::class, 'update'])->middleware('can:solicitud.edit')->name('solicitud.update');
Route::delete('solicitud/{solicitud}', [SolicitudController::class, 'destroy'])->middleware('can:solicitud.delete')->name('solicitud.destroy');
Route::get('solicitud/{solicitud}/aprobar', [SolicitudController::class, 'aprobar'])->middleware('can:jefe-red')->name('solicitud.aprobar');
Route::post('solicitud/rechazar', [SolicitudController::class, 'rechazar'])->middleware('can:jefe-red')->name('solicitud.sol_rechazar');
Route::get('pendientes', [SolicitudController::class, 'reject'])->middleware('can:jefe-red')->name('solicitud.reject');
Route::get('solicitud/{solicitud}/reporte_rechazado', [SolicitudController::class, 'PDF_rechazado'])->middleware('permission:jefe-red|Monitor')->name('solicitud.PDFrechazado');
Route::post('solicitud/{solicitud}/guardar_ampliacion', [SolicitudController::class, 'guardarAmpliacion'])->name('solicitud.guardarAmpliacion');
Route::get('solicitud/{solicitud}/comprobante_solicitud', [SolicitudController::class, 'comprobante_solicitud'])->name('solicitud.comprobante_solicitud');
Route::get('solicitud/{solicitud}/obtener_ampliacion', [SolicitudController::class, 'obtenerAmpliacion'])->name('solicitud.obtenerAmpliaciones');
Route::post('solicitud/solicitud_escaneada', [SolicitudController::class, 'solicitud_escaneada'])->name('solicitud.escaneada');
Route::get('solicitud/{solicitud}/form_rechazar', [SolicitudController::class, 'form_rechazado'])->middleware('can:jefe-red')->name('solicitud.form_rechazado');
Route::get('solicitud/avance', [SolicitudController::class, 'avance'])->name('solicitud.avance');
Route::post('solicitud/pasos_solicitud', [SolicitudController::class, 'pasos_solicitud'])->name('solicitud.pasos_solicitud');
Route::post('solicitud/cambiar_estado', [SolicitudController::class, 'cambiar_estado'])->name('solicitud.cambiar_estado');
Route::get('solicitud/{id}/reporte_historicos', [SolicitudController::class, 'reporte_historicos'])->name('solicitud.reporte_historicos');

// Crud solicitud

// Route::resource('informes', InformeController::class);
Route::get('Informes', [InformeController::class, 'index'])->middleware('can:informes.index')->name('informes.index');
Route::get('Informes/inspeccionados', [InformeController::class, 'inspeccionado'])->name('informes.inspeccionados');
Route::get('Informes/autorizados', [InformeController::class, 'autorizado'])->name('informes.autorizado');
Route::get('Informes/concluidos', [InformeController::class, 'concluido'])->name('informes.concluido');
Route::get('Informes/informes_ejecutados', [InformeController::class, 'informes_ejecutados'])->middleware('can:informes-ejecucion')->name('informes.informes_ejecutados');
Route::get('Informes/registrar_informes', [InformeController::class, 'create'])->middleware('can:informes.create')->name('informes.create');
Route::post('Informes/registrar_informe', [InformeController::class, 'store'])->middleware('can:informes.create')->name('informes.store');
Route::post('Informes/update_costos', [InformeController::class, 'update_costos'])->name('informes.update_costos');
Route::get('Informes/{informe}/edit', [InformeController::class, 'edit'])->middleware('can:informes.edit')->name('informes.edit');
Route::get('Informes/{informe}/show', [InformeController::class, 'show'])->name('informes.show');
Route::get('Informes/{informe}/show_costos', [InformeController::class, 'show_costos'])->name('informes.show_costos');
Route::put('Informes/{informe}', [InformeController::class, 'update'])->middleware('can:informes.edit')->name('informes.update');
Route::get('PDF/{informe}/PDFinforme', [PDFController::class, 'PDF'])->name('descargarPDF.informe');
Route::delete('Informes/{Informe}', [InformeController::class, 'destroy'])->name('informes.destroy');
Route::get('Informes/{informe}/registrar_material', [InformeController::class, 'registrar_material'])->name('informes.registrar_material');
Route::post('Informes/{Informe}/autorizar', [InformeController::class, 'autorizar'])->middleware('can:jefe-red')->name('informes.autorizar');
Route::get('Informes/{informe}/rechazar', [InformeController::class, 'no_autorizar'])->middleware('can:jefe-red')->name('informes.no_autorizar');
Route::get('Informes/{informe}/firmar', [InformeController::class, 'firmar_informe'])->middleware('can:jefe-red')->name('informes.firmar');
Route::get('Informes/{informe}/devolver_asignado', [InformeController::class, 'devolver_asignado'])->middleware('can:jefe-red')->name('informes.devolver_asignado');
Route::get('Informes/{informe}/aprobar_proyecto', [InformeController::class, 'aprobar_proyecto'])->middleware('can:Proyectista')->name('informes.aprobar_proyecto');
Route::post('Informes/{informe}/solicitar_autorizacion', [InformeController::class, 'solicitar_autorizacion'])->middleware('can:informes.edit')->name('informes.solicitar_autorizacion');
Route::post('Informes/esperar_aprobacion', [InformeController::class, 'esperar_aprobacion'])->name('informes.esperar_aprobacion');
Route::post('Informes/reversa_aprobacion', [InformeController::class, 'reversa_aprobacion'])->name('informes.reversa_aprobacion');
Route::post('Informes/verificacion_estado', [InformeController::class, 'verificacion_estado'])->name('informes.verificacion_estado');
Route::get('Informes/ejecutados/{fecha_inicio?}/{fecha_fin?}', [InformeController::class, 'ejecutados'])->name('informes.ejecutados');
// Route::post('Informes/vista_ejecutados', [InformeController::class, 'vista_ejecutados'])->name('informes.vista_ejecutados');
Route::get('Informes/reporte_ejecutados/{fecha_i?}/{fecha_f?}', [InformeController::class, 'reporte_ejecutados'])->name('informes.reporte_ejecutados');
// Modificacion al admin
Route::post('Informes/paso_atras', [InformeController::class, 'paso_atras'])->name('informes.paso_atras');

// CRUD MATERIALES
Route::resource('materials', MaterialController::class)->middleware('can:jefe-red')->names('materials');

// Asigacion de materiales a los informes´
Route::resource('material_informe', Materials_informesController::class)->names('material_informe');
Route::delete('material_informe/{mat_inf}/eliminar', [Materials_informesController::class, 'eliminar_lista'])->name('material_informe.eliminar');

Route::get('PDF/{informe}/PDFpedido', [PDFController::class, 'PDF_pedido'])->name('pedidoPDF.informe');
Route::get('PDF/{informe}/PDFreporte_ampliacion', [PDFController::class, 'PDF_informe_material'])->name('reportePDF.informe_material');
Route::get('PDF/{informe}/PDFreporte_descargo_material', [PDFController::class, 'PDF_informe_descargo_material'])->name('reportePDF.informe_descargo_material');
Route::get('PDF/{id}/acta_final', [PDFController::class, 'acta_final'])->name('reportePDF.acta_final');


// Asigacion de Solicitudes a Inspectores
Route::resource('cronograma', CronogramaController::class)->names('cronograma');
Route::get('Cronograma/registro_cronograma', [CronogramaController::class, 'mostrar'])->name('cronograma.reporte');
Route::get('PDF/{fecha_i?}/{fecha_f?}/{user_id?}/PDFcronograma', [PDFController::class, 'PDF_cronograma'])->name('descargarPDF.cronograma');

//___________________________________DESCARGO DE MATERIALES____________________________________________________________________
Route::resource('descargo', DescargoController::class)->names('descargo'); //Metodo index
// APORTE MATERIAL VECINOS
Route::get('Descargos/{descargo}/{fecha_descargo?}/{valor?}/mostrar_aportes_v', [DescargoController::class, 'mostrar_aportes_v'])->name('descargo.mostrar_aportes_v');
Route::get('Descargos/{descargo}/{fecha_descargo?}/{valor?}/crear_aportes_v', [DescargoController::class, 'crear_aport_v'])->name('descargo.crear_aport_v');
Route::post('Descargos/registrar_aporte_v', [DescargoController::class, 'registrar_aporte_v'])->name('descargo.registrar_aporte_v');
Route::delete('Aporte_eliminar/{descargo}/{fecha_descargo?}/{valor?}', [DescargoController::class, 'eliminar_aporte'])->name('descargo.eliminar_aporte');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Jetstream\HasTeams;
use Laravel\Sanctum\HasApiTokens;

use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use HasTeams;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use HasRoles;


    protected $fillable = [
        'name', 'email', 'password','tipo_user'
    ];


    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];


    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    protected $appends = [
        'profile_photo_url',
    ];
    public function adminlte_desc(){
        return "Usuario Elapas";
    }
    public function adminlte_profile_url(){
        return "user/profile";
    }


    public function solicituds()
    {
        return $this->belongsToMany('App\Models\Solicitud','cronogramas','user_id','solicitud_id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\Models\User;
use Dotenv\Validator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;
class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:users.index')->only('index');
        $this->middleware('can:users.edit')->only('edit','update');
    }
    public function index()
    {
        $users = User::all();
        return view('users.index',compact('users'));
    }


    public function create()
    {
        $roles = Role::all();
        return view('users.create',compact('roles'));
    }

    public function store(Request $request)
    {

       $request->validate([
           'name'=>'required|min:5|max:100|unique:users',
           'email'=>'required|min:3|max:20|unique:users',
           'password'=>'required',
           'tipo_user'=>'required',
       ]);

       User::create($request->only('name','email','tipo_user')+[
            'password'=>bcrypt($request->input('password')),
            'email_verified_at' => now(),
       ]);
       return redirect()->route('users.index')->with('crear','ok');
    }


    public function show($id)
    {
        //
    }


    public function edit(User $user)
    {
        $roles = Role::all();
        // return $roles;
        return view('users.edit',compact('user', 'roles'));
    }


    public function update(Request $request, User $user)
    {
        if ($request->roles==1) {
            $user->tipo_user = "Administrador";
            $user->save();
        }
        elseif($request->roles==2){
            $user->tipo_user = "Jefe de red";
            $user->save();
        }
        elseif($request->roles==3){
            $user->tipo_user = "Inspector";
            $user->save();
        }
        elseif($request->roles==4){
            $user->tipo_user = "Secretaria";
            $user->save();
        }
        else{
            $user->tipo_user = "";
            $user->save();
        }

        $user->roles()->sync($request->roles);
        return redirect()->route('users.edit', $user)->with('info','Se asigno los roles correctamente');
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Registrar Usuario')

@section('content_header')
    <h1>USUARIOS</h1>
@stop

@section('content')
<div class="justify-content-center row">
    <!-- left column -->
    <div class="col-md-6">
    <!-- general form elements -->
        <div class="card card-primary ">
        <div class="card-header">
            <h3 class="card-title">Registrar Usuario</h3>
        </div>
        <!-- /.card-header -->
        <!-- formulario inicio -->
        <form action="{{route('users.store')}}" method="POST" class="create" role="form" id="form_materials" autocomplete="off">
            @csrf
            <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error )
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="input-group mb-3">
                    <input type="text" name="name" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}"
                           value="{{ old('name') }}" placeholder="{{ __('adminlte::adminlte.full_name') }}" autofocus>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user {{ config('adminlte.classes_auth_icon', '') }}"></span>
                        </div>
                    </div>
                    @if($errors->has('name'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('name') }}</strong>
                        </div>
                    @endif
                </div>
                <div class="input-group mb-3">
                    <input type="text" name="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}"
                           value="{{ old('email') }}" placeholder="{{ __('adminlte::adminlte.email') }}">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope {{ config('adminlte.classes_auth_icon', '') }}"></span>
                        </div>
                    </div>
                    @if($errors->has('email'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('email') }}</strong>
                        </div>
                    @endif
                </div>

                        {{-- Password field --}}
                <div class="input-group mb-3">
                    <input type="password" name="password"
                        class="form-control {{ $errors->has('password') ? 'is-invalid' : '' }}"
                        placeholder="{{ __('adminlte::adminlte.password') }}">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock {{ config('adminlte.classes_auth_icon', '') }}"></span>
                        </div>
                    </div>
                    @if($errors->has('password'))
                        <div class="invalid-feedback">
                            <strong>{{ $errors->first('password') }}</strong>
                        </div>
                    @endif
                </div>

                <div class="form-group">
                    <label for="nombre_material">Tipo de Usuario</label>
                    <select class="form-control" name="tipo_user" id="tipo_user">
                        <option value="" disabled selected>__SELECCIONE__</option>
                        @foreach ($roles as $role)
                        <option value="{{$role->name}}">{{$role->name}}</option>
                        @endforeach
                        {{-- <option value="Inspector">Inspector</option>
                        <option value="Secretaria">Secretaria</option>
                        <option value="Jefe-red">Jefe de Red</option>
                        <option value="Jefe-red">Jefe de Red</option> --}}
                      </select>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-block btn-primary">Registrar</button>
            </div>
        </form>
        {{-- Fin de formulario --}}
        </div>
    </div>
</div>

@stop

@section('js')
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    @if(session('crear')=='Ok')
        <script>
            Swal.fire(
                'Eliminado!',
                'Su registro ha sido eliminado.',
                'success'
                )
        </script>
    @else
        @if($errors->any())
            <script>
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Algo salió mal!',
                })

            </script>
        @endif
    @endif
    <script>
    $('.select2').select2();
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Asignar Rol')

@section('content_header')
    <h1>ASIGNAR UN ROL</h1>
@stop

{{-- @section('content')
    <p>Bienvenido.</p>
@stop --}}
@section('content')

    @if(session('info'))
        <div class="alert alert-success">
            <strong>
                {{session('info')}}
            </strong>
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            <p class="h5">Nombre:</p>
            <p class="form-control">{{$user->name}}</p>
            <h2 class="h5">Listado de roles</h2>
            {!! Form::model($user, ['route'=>['users.update', $user], 'method'=>'put'])!!}
                @foreach ($roles as $role)
                    <div>
                        <label>
                            {!! Form::checkbox('roles', $role->id, null, ['class'=>'mr-1']) !!}
                            {{$role->name}}
                        </label>
                    </div>
                @endforeach
                {!! Form::submit('Asignar rol', ['class'=>'btn btn-primary mt-2']) !!}
            {!! Form::close() !!}
        </div>

    </div>
@stop

@section('js')
    <script>
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Uuarios')

@section('content_header')
<a href="{{route('users.create')}}" class="btn btn-success btn-rounded" style="float: right;">
    Registrar Usuario <i class="fa fa-plus-square"></i>
</a>
    <h1>LISTA DE USUARIOS</h1>
   
@stop


@section('content')

<div class="table table-bordered table-hover dataTable table-responsive">
    <table class="table table-bordered datatable" id="example">
    <thead>
      <tr>	
        <th width="50">Id</th>
        <th>Nombre</th>
        <th width="350">Email</th>
        <th>Roles</th>
        <th width="100">Acciones</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($users as $user)
            <tr>
                <td>{{$user->id}}</td>
                <td>{{$user->name}}</td>
                <td>{{$user->email}}</td>
                <td>
                  <ul>
                  @foreach($user->roles as $rol)
                  <li>{{$rol->name}}</li>
                  @endforeach
                  </ul>
                </td>
                <td>
                    <a href='{{route('users.edit',$user->id)}}' 
                    class='btn btn-info btn-icon btn-xs'>Asignar rol <i class="fas fa-pencil-alt"></i></a>
                    <form action="">
                        @csrf
                        {{-- @method('delete') --}}
                        {{-- <button class='btn btn-danger btn-icon btn-xs' type="submit">Eliminar  <i class="fas fa-trash"></i></button> --}}
                    </form>
                </td>
            </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Acciones</th>
        </tr>
    </tfoot>
</table>
</div>
@stop

@section('js')
    <script>
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop