routes/web.php
<?php

use App\Http\Controllers\ActividadManoObraController;
use App\Http\Controllers\ArchivosSolicitudController;
use App\Http\Controllers\CronogramaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\inicioControl;
use App\Http\Controllers\SolicitudController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\InformeController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\Materials_informesController;
use App\Http\Controllers\DescargoController;
use App\Http\Controllers\EjecucionController;
use App\Http\Controllers\Mano_ObrasController;
use App\Http\Controllers\MonitorController;
use App\Http\Controllers\PDFController;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

Route::get('/', inicioControl::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('dash.index');
})->name('dash');
// CRUD USUARIOS
Route::resource('users', UserController::class)->only('index', 'edit', 'update', 'create', 'store')->names('users');
// Crud SOLICITUD
Route::get('Lista_solicitud', [SolicitudController::class, 'index'])->middleware('can:solicitud.index')->name('solicitud.index');
Route::get('solicitud/registrar_solicitud', [SolicitudController::class, 'create'])->middleware('can:solicitud.create')->name('solicitud.create');
Route::post('solicitud/registrar_solicitud', [SolicitudController::class, 'store'])->name('solicitud.store');
Route::get('solicitud/{solicitud}/edit', [SolicitudController::class, 'edit'])->middleware('can:solicitud.edit')->name('solicitud.edit');
Route::put('solicitud/{solicitud}', [SolicitudController::class, 'update'])->middleware('can:solicitud.edit')->name('solicitud.update');
Route::delete('solicitud/{solicitud}', [SolicitudController::class, 'destroy'])->middleware('can:solicitud.delete')->name('solicitud.destroy');
Route::get('solicitud/{solicitud}/aprobar', [SolicitudController::class, 'aprobar'])->middleware('can:jefe-red')->name('solicitud.aprobar');
Route::post('solicitud/rechazar', [SolicitudController::class, 'rechazar'])->middleware('can:jefe-red')->name('solicitud.sol_rechazar');
Route::get('pendientes', [SolicitudController::class, 'reject'])->middleware('can:jefe-red')->name('solicitud.reject');
Route::get('solicitud/{solicitud}/reporte_rechazado', [SolicitudController::class, 'PDF_rechazado'])->middleware('permission:jefe-red|Monitor')->name('solicitud.PDFrechazado');
Route::post('solicitud/{solicitud}/guardar_ampliacion', [SolicitudController::class, 'guardarAmpliacion'])->name('solicitud.guardarAmpliacion');
Route::get('solicitud/{solicitud}/comprobante_solicitud', [SolicitudController::class, 'comprobante_solicitud'])->name('solicitud.comprobante_solicitud');
Route::get('solicitud/{solicitud}/obtener_ampliacion', [SolicitudController::class, 'obtenerAmpliacion'])->name('solicitud.obtenerAmpliaciones');
Route::post('solicitud/solicitud_escaneada', [SolicitudController::class, 'solicitud_escaneada'])->name('solicitud.escaneada');
Route::get('solicitud/{solicitud}/form_rechazar', [SolicitudController::class, 'form_rechazado'])->middleware('can:jefe-red')->name('solicitud.form_rechazado');
Route::get('solicitud/avance', [SolicitudController::class, 'avance'])->name('solicitud.avance');
Route::post('solicitud/pasos_solicitud', [SolicitudController::class, 'pasos_solicitud'])->name('solicitud.pasos_solicitud');
Route::post('solicitud/cambiar_estado', [SolicitudController::class, 'cambiar_estado'])->name('solicitud.cambiar_estado');
Route::get('solicitud/{id}/reporte_historicos', [SolicitudController::class, 'reporte_historicos'])->name('solicitud.reporte_historicos');

// Crud solicitud

// Route::resource('informes', InformeController::class);
Route::get('Informes', [InformeController::class, 'index'])->middleware('can:informes.index')->name('informes.index');
Route::get('Informes/inspeccionados', [InformeController::class, 'inspeccionado'])->name('informes.inspeccionados');
Route::get('Informes/autorizados', [InformeController::class, 'autorizado'])->name('informes.autorizado');
Route::get('Informes/concluidos', [InformeController::class, 'concluido'])->name('informes.concluido');
Route::get('Informes/informes_ejecutados', [InformeController::class, 'informes_ejecutados'])->middleware('can:informes-ejecucion')->name('informes.informes_ejecutados');
Route::get('Informes/registrar_informes', [InformeController::class, 'create'])->middleware('can:informes.create')->name('informes.create');
Route::post('Informes/registrar_informe', [InformeController::class, 'store'])->middleware('can:informes.create')->name('informes.store');
Route::post('Informes/update_costos', [InformeController::class, 'update_costos'])->name('informes.update_costos');
Route::get('Informes/{informe}/edit', [InformeController::class, 'edit'])->middleware('can:informes.edit')->name('informes.edit');
Route::get('Informes/{informe}/show', [InformeController::class, 'show'])->name('informes.show');
Route::get('Informes/{informe}/show_costos', [InformeController::class, 'show_costos'])->name('informes.show_costos');
Route::put('Informes/{informe}', [InformeController::class, 'update'])->middleware('can:informes.edit')->name('informes.update');
Route::get('PDF/{informe}/PDFinforme', [PDFController::class, 'PDF'])->name('descargarPDF.informe');
Route::delete('Informes/{Informe}', [InformeController::class, 'destroy'])->name('informes.destroy');
Route::get('Informes/{informe}/registrar_material', [InformeController::class, 'registrar_material'])->name('informes.registrar_material');
Route::post('Informes/{Informe}/autorizar', [InformeController::class, 'autorizar'])->middleware('can:jefe-red')->name('informes.autorizar');
Route::get('Informes/{informe}/rechazar', [InformeController::class, 'no_autorizar'])->middleware('can:jefe-red')->name('informes.no_autorizar');
Route::get('Informes/{informe}/firmar', [InformeController::class, 'firmar_informe'])->middleware('can:jefe-red')->name('informes.firmar');
Route::get('Informes/{informe}/devolver_asignado', [InformeController::class, 'devolver_asignado'])->middleware('can:jefe-red')->name('informes.devolver_asignado');
Route::get('Informes/{informe}/aprobar_proyecto', [InformeController::class, 'aprobar_proyecto'])->middleware('can:Proyectista')->name('informes.aprobar_proyecto');
Route::post('Informes/{informe}/solicitar_autorizacion', [InformeController::class, 'solicitar_autorizacion'])->middleware('can:informes.edit')->name('informes.solicitar_autorizacion');
Route::post('Informes/esperar_aprobacion', [InformeController::class, 'esperar_aprobacion'])->name('informes.esperar_aprobacion');
Route::post('Informes/reversa_aprobacion', [InformeController::class, 'reversa_aprobacion'])->name('informes.reversa_aprobacion');
Route::post('Informes/verificacion_estado', [InformeController::class, 'verificacion_estado'])->name('informes.verificacion_estado');
Route::get('Informes/ejecutados/{fecha_inicio?}/{fecha_fin?}', [InformeController::class, 'ejecutados'])->name('informes.ejecutados');
// Route::post('Informes/vista_ejecutados', [InformeController::class, 'vista_ejecutados'])->name('informes.vista_ejecutados');
Route::get('Informes/reporte_ejecutados/{fecha_i?}/{fecha_f?}', [InformeController::class, 'reporte_ejecutados'])->name('informes.reporte_ejecutados');
// Modificacion al admin
Route::post('Informes/paso_atras', [InformeController::class, 'paso_atras'])->name('informes.paso_atras');

// CRUD MATERIALES
Route::resource('materials', MaterialController::class)->middleware('can:jefe-red')->names('materials');

// Asigacion de materiales a los informes´
Route::resource('material_informe', Materials_informesController::class)->names('material_informe');
Route::delete('material_informe/{mat_inf}/eliminar', [Materials_informesController::class, 'eliminar_lista'])->name('material_informe.eliminar');

Route::get('PDF/{informe}/PDFpedido', [PDFController::class, 'PDF_pedido'])->name('pedidoPDF.informe');
Route::get('PDF/{informe}/PDFreporte_ampliacion', [PDFController::class, 'PDF_informe_material'])->name('reportePDF.informe_material');
Route::get('PDF/{informe}/PDFreporte_descargo_material', [PDFController::class, 'PDF_informe_descargo_material'])->name('reportePDF.informe_descargo_material');
Route::get('PDF/{id}/acta_final', [PDFController::class, 'acta_final'])->name('reportePDF.acta_final');


// Asigacion de Solicitudes a Inspectores
Route::resource('cronograma', CronogramaController::class)->names('cronograma');
Route::get('Cronograma/registro_cronograma', [CronogramaController::class, 'mostrar'])->name('cronograma.reporte');
Route::get('PDF/{fecha_i?}/{fecha_f?}/{user_id?}/PDFcronograma', [PDFController::class, 'PDF_cronograma'])->name('descargarPDF.cronograma');

//___________________________________DESCARGO DE MATERIALES____________________________________________________________________
Route::resource('descargo', DescargoController::class)->names('descargo'); //Metodo index
// APORTE MATERIAL VECINOS
Route::get('Descargos/{descargo}/{fecha_descargo?}/{valor?}/mostrar_aportes_v', [DescargoController::class, 'mostrar_aportes_v'])->name('descargo.mostrar_aportes_v');
Route::get('Descargos/{descargo}/{fecha_descargo?}/{valor?}/crear_aportes_v', [DescargoController::class, 'crear_aport_v'])->name('descargo.crear_aport_v');
Route::post('Descargos/registrar_aporte_v', [DescargoController::class, 'registrar_aporte_v'])->name('descargo.registrar_aporte_v');
Route::delete('Aporte_eliminar/{descargo}/{fecha_descargo?}/{valor?}', [DescargoController::class, 'eliminar_aporte'])->name('descargo.eliminar_aporte');

resources/views/material_informe/create.blade.php
@extends('adminlte::page')

@section('title', 'Asign_Material')

@section('content_header')
    <style>
        #map {
            margin-top: 20px;
            width: 100%;
            height: 400px;
        }
    </style>
    <h1>Asignacion de Material
        {{-- {{ print_r($data["info"]) }} --}}
        @can('inspector')
            <a href="{{ route('informes.autorizado') }}" class="btn btn-danger btn-rounded" style="float: right;">
                <i class="fa fa-arrow-circle-left"></i> Inspecciones Autorizadas
            </a>
        @endcan
        @can('users.index')
            <a href="{{ route('informes.autorizado') }}" class="btn btn-danger btn-rounded" style="float: right;">
                <i class="fa fa-arrow-circle-left"></i> Inspecciones Autorizadas
            </a>
        @endcan
    </h1>

@stop

@section('content')
    <div id="contenedor-tabla">
        <div class="justify-content-center row">
            <div class="col-md-4 ">
                <div class="card card-primary h-100">
                    <div class="card-header">
                        INFORMACION DE LA AMPLIACION
                    </div>
                    <div class="card-body">
                        <div>
                            <label for="informe">Nombre del Solicitante</label>
                            <div class="input-group ">
                                <p>{{ $informe->solicitud->nombre_sol }}</p>
                            </div>
                        </div>
                        <div>
                            <label for="informe">Zona</label>
                            <div class="input-group ">
                                <p>{{ $informe->solicitud->zona_sol }}</p>
                            </div>
                        </div>
                        <div>
                            <label for="informe">Dentro del Area de Concesión: </label> {{ $informe->espesifiar_in }}
                            <div class="input-group ">
                            </div>
                        </div>
                        <div>
                            <label for="informe">Longitud de la Ampliación: </label> {{ $informe->longitud_inspector }}
                            metros
                            <div class="input-group ">
                            </div>
                        </div>
                        <div>
                            <label for="informe">Diametro de la Ampliación : </label> {{ $informe->diametro_in }} pulgadas
                            <div class="input-group ">
                            </div>
                        </div>
                        <div>
                            <label for="informe">Condiciones de Rasante: </label> {{ $informe->condicion_rasante }}
                            <div class="input-group ">
                            </div>
                        </div>
                        <button type="button" class="btn btn-warning btn-icon w-100"
                            onclick="visualizarMapa({{ $informe->x_exact }},{{ $informe->y_exact }}, '{{ route('solicitud.obtenerAmpliaciones', $informe->solicitud_id) }}')">
                            <i class="fas fa-eye"></i> Visualizar Mapa
                        </button>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card card-primary  h-100">
                    <div class="card-header">
                        <h3 class="card-title">ASIGNAR MATERIAL</h3>
                    </div>
                    {{-- <form action="{{ route('material_informe.store') }}" method="POST" role="form" id="form_materials"
                        autocomplete="off">
                        @csrf
                        <div class="card-body">
                            <div class="col-md-12"> --}}
                    <form action="{{ route('material_informe.store') }}" method="POST" role="form" id="form_materials">
                        @csrf
                        <div class="card-body">
                            <input type="hidden" name="id_informe" id="id_informe" value="{{ $informe->id }}">
                            <div class="form-group">
                                <label for="nombre_material">Descripcion Material</label>
                                <div class="input-group ">
                                    <select class="form-control select2" onchange="cambiarMaterial()" name="id_material"
                                        id="id_material" required>
                                        <option value="0" selected>---Seleccione Material---</option>
                                        @foreach ($materials as $material)
                                            <option value="{{ $material->id }}-{{ $material->precio_unitario }}">
                                                {{ $material->codigo . ' - ' . $material->nombre_material . ' ( U. ' . $material->unidad_med . ' )( C.' . $material->cantidad . ' )' }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <label for="cantidad">Cantidad de Material</label>
                                    <div class="input-group col-md-12 ">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                                        </div>
                                        <input type="number" min="1" name="cantidad" id="cantidad"
                                            class="form-control" placeholder="Cantidad de Material" required>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label for="observador">Proveedor</label>
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div>
                                                <p style="margin-right: 5px">Elapas
                                                    <input type="radio" onchange="habilitarPrecio()" value="Elapas"
                                                        checked name="observador" style="margin-top:5px; margin-right: 3px">
                                                </p>
                                            </div>
                                        </div>
                                        <div class="input-group-prepend">
                                            <div>
                                                <p style="margin-right: 5px"> Terceros
                                                    <input type="radio" onchange="habilitarPrecio()" value="Terceros"
                                                        name="observador" style="margin-top:5px; margin-right: 3px">
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6">
                                    <label for="cantidad">Precio Unitario</label>
                                    <div class="input-group col-md-12 ">
                                        <input type="number" min="0.00" step="0.01" name="precio" id="precio"
                                            class="form-control" placeholder="Precio unitario de Material" disabled
                                            required>
                                    </div>
                                    <input type="hidden" id="precio_elapas" name="precio_elapas">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <button type="submit" class="btn btn-block btn-primary ">Registrar</button>
                        </div>
                    </form>
                    {{-- </div>
                        </div> --}}
                </div>
            </div>
            <div class="table table-bordered table-hover dataTable table-responsive">
                <table class="table table-bordered datatable" id="example">
                    <thead>
                        <tr>
                            <th width="170">ID</th>
                            <th>MATERIAL</th>
                            <th width="150">UNIDAD <br> MEDIDA</th>
                            <th width="150">CANTIDAD <br> SOLICITADA </th>
                            <th>PRECIO <br>UNITARIO</th>
                            <th width="150">PROVEEDOR</th>
                            <th width="150">ACCIONES</th>
                        </tr>
                    </thead>
                    <tbody id="contenedor-materiales">
                        @foreach ($mat_inf as $mat)
                            <tr>
                                <td>{{ $mat->id }}</td>
                                <td align="center">{{ $mat->material_n }}</td>
                                <td>{{ $mat->unidad }}</td>
                                <td>{{ $mat->cantidad }}</td>
                                <td>{{ $mat->precio }}</td>
                                <td>{{ $mat->observador }}</td>
                                <td>
                                    <form action="{{ route('material_informe.eliminar', $mat->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-icon btn-xs" type="submit">Eliminar <i
                                                class="fas fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div id="contenedor-mapa" style="display: none">
        <input type="hidden" id="obtenerAmpliaciones">
        <button onclick="mostrarTabla(false)" class="btn btn-primary"> <i class="fas fa-arrow-circle-left"></i>
            Volver
        </button>
        <div class="col-md-12">
            <div id="map">
            </div>
        </div>
    </div>
@stop

@section('js')
    <script>
        const camara_icono = "{{ asset('images/alc_camara.png') }}";
        const ubicacion_icono = "{{ asset('images/marker-icon.png') }}"
    </script>
    <script>
        $('.select2').select2();
    </script>
    <script src="{{ asset('vendor/leaflet/js/leaflet.js') }}" crossorigin=""></script>
    <script src="{{ asset('vendor/leaflet/js/esri-leaflet.js') }}" crossorigin=""></script>
    <script src="{{ asset('vendor/leaflet/js/esri-leaflet-geocoder.js') }}" crossorigin=""></script>
    <script src="{{ asset('vendor/leaflet/js/easy-button.js') }}"></script>
    <script src="{{ asset('js/betterwms.js') }}"></script>
    <script src="{{ asset('js/mapas.js') }}"></script>
    <script src="{{ asset('js/material_informe.js') }}"></script>
@stop
@section('css')
    <link rel="stylesheet" href="{{ asset('vendor/leaflet/css/leaflet.css') }}" crossorigin="" />
    <link rel="stylesheet" href="{{ asset('vendor/leaflet/css/esri-leaflet-geocoder.css') }}" crossorigin="">
    <link rel="stylesheet" href="{{ asset('vendor/leaflet/css/easy-button.css') }}">
@stop

resources/views/material_informe/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Material')

@section('content_header')
    <h1>Editar Material</h1>
@stop

@section('content')
<div class="justify-content-center row">
    <!-- left column -->
    <div class="col-md-8">
    <!-- general form elements -->
        <div class="card card-primary ">
        <div class="card-header">
            <h3 class="card-title">Editar Material</h3>
        </div>
        <!-- /.card-header -->
        <!-- formulario inicio -->
        <form action="{{route('materials.update',$material)}}" method="POST" role="form" id="form_materials" autocomplete="off">
            @csrf
            @method('put')
            <div class="card-body">
                <div class="form-group">
                    <label for="nombre_material">Nombre del material</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="text" name="nombre_material" id="nombre_material" class="form-control" value="{{$material->nombre_material}}" placeholder="nombre del material">
                    </div>
                </div>
                <div class="form-group">
                    <label for="nombre_material">Observaciones</label>
                    <div class="input-group ">
                        <textarea name="observaciones" id="observaciones" class="form-control" >{{$material->observaciones}}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="nombre_material">Estado</label>
                    <select class="form-control" name="estado" id="estado">
                        <option value="disponible">Disponible</option>
                        <option value="no disponible">No Disponible</option>
                      </select>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-block btn-primary">Registrar</button>
            </div>
        </form>
        {{-- Fin de formulario --}}
        </div>
    </div>
</div>

@stop

@section('js')
    <script>
    $('.select2').select2();
    </script>
@stop
@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

resources/views/material_informe/editar_costo.blade.php
@if ($mat_inf == [])
    <p>No se asignaron materiales</p>
@else
    {{-- <h3>ID: {{ $primer_id->id }}</h3>
<h3>Total: {{ $ultimo_id->id }}</h3>
<h3>{{ $total_ids }}</h3> --}}
    <div class="table table-bordered table-hover dataTable table-responsive">
        <table class="table table-bordered datatable" id="example">
            <thead>
                <tr>
                    <th width="170">ID</th>
                    <th>MATERIAL</th>
                    {{-- <th width="150">UNIDAD <br> MEDIDA</th> --}}
                    <th width="150">CANTIDAD <br> SOLICITADA </th>
                    <th width="150">PRECIO <br> UNITARIO </th>
                    <th width="150">Costo</th>
                    <th width="150">Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($mat_inf as $value)
                    <tr>
                        <td>{{ $value->id }}</td>
                        <td align="center">{{ $value->material_n }}</td>
                        {{-- <td>{{ $value->u_medida }}</td> --}}
                        <td>
                            <input style="width: 80;" type="number" name="cantidad_solicitada" id="cantidad_solicitada" value="{{ $value->cantidad }}">
                        </td>
                        <td>
                            <input style="width: 80;" type="number" name="precioUnitario" id="precioUnitario"
                                value="{{ $value->precio_unitario }}">
                        </td>
                        <td>
                            <input type="hidden" name="id" id="id" value="{{ $value->id }}">
                            <input style="width: 80;" type="number" name="precioTotal" id="precioTotal"
                                value="{{ $value->sub_total }}">
                        </td>
                        <td>
                            <button type="button" class="d-inline btn btn-warning btn-icon editCost" title="Modificar Costo">
                                Editar Costo <i class="fas fa-pencil-alt"></i>
                            </button>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    </div>
@endif
@section('js')
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script>
        const ruta_update_costos = "{{ route('informes.update_costos') }}"
    </script>
    <script src="{{ asset('js/informes.js') }}"></script>
    @if (session('modificado') == 'ok')
        <script>
            Swal.fire(
                'Modificado!',
                'Su registro ha sido Corregido.',
                'success'
            )
        </script>
    @endif
    @if (session('modificado') == 'error')
        <script>
            Swal.fire(
                'Error!',
                'Error al realizar la peticion.',
                'danger'
            )
        </script>
    @endif
@endsection

resources/views/material_informe/index.blade.php
    <!-- /.card-header -->
    <!-- formulario inicio -->

    <a href="{{route('informes.registrar_material',$informe->id)}}" class="btn btn-warning btn-rounded" style="float: right; margin-right: 5px;">
        Registrar material <i class="fas fa-fw fa-box-open"></i>
    </a>


@if($mat_inf==[])
    <p>No se asignaron materiales</p>
@else
<div class="table table-bordered table-hover dataTable table-responsive">
    <table class="table table-bordered datatable" id="example">
    <thead>
        <tr>
            <th width="170">ID</th>
            <th >MATERIAL</th>
            <th width="150">CANTIDAD <br> SOLICITADA </th>
            <th width="150">UNIDAD <br> MEDIDA</th>
            <th width="150">ACCIONES</th>
        </tr>
    </thead>
    <tbody>

        @foreach($mat_inf as $value)
        <tr>
            <td>{{$value->id}}</td>
            <td align="center">{{$value->material_n}}</td>
            <td>{{$value->cantidad}}</td>
            <td>{{$value->u_medida}}</td>
            <td>
                <form action="{{route('material_informe.destroy',$value->id)}}" method="POST">
                    @csrf
                    @method('delete')
                    <button class='btn btn-danger btn-icon btn-xs' type="submit">Eliminar  <i class="fas fa-trash"></i></button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
</div>
@endif


<script>
    $('.select2').select2();
    $.fn.modal.Constructor.prototype.enforceFocus = function() {};
</script>