routes/web.php
<?php

use App\Http\Controllers\ActividadManoObraController;
use App\Http\Controllers\ArchivosSolicitudController;
use App\Http\Controllers\CronogramaController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\inicioControl;
use App\Http\Controllers\SolicitudController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\InformeController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\Materials_informesController;
use App\Http\Controllers\DescargoController;
use App\Http\Controllers\EjecucionController;
use App\Http\Controllers\Mano_ObrasController;
use App\Http\Controllers\MonitorController;
use App\Http\Controllers\PDFController;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

Route::get('/', inicioControl::class);

Route::middleware(['auth:sanctum', 'verified'])->get('/dash', function () {
    return view('dash.index');
})->name('dash');
// CRUD USUARIOS
Route::resource('users', UserController::class)->only('index', 'edit', 'update', 'create', 'store')->names('users');
// Crud SOLICITUD
Route::get('Lista_solicitud', [SolicitudController::class, 'index'])->middleware('can:solicitud.index')->name('solicitud.index');
Route::get('solicitud/registrar_solicitud', [SolicitudController::class, 'create'])->middleware('can:solicitud.create')->name('solicitud.create');
Route::post('solicitud/registrar_solicitud', [SolicitudController::class, 'store'])->name('solicitud.store');
Route::get('solicitud/{solicitud}/edit', [SolicitudController::class, 'edit'])->middleware('can:solicitud.edit')->name('solicitud.edit');
Route::put('solicitud/{solicitud}', [SolicitudController::class, 'update'])->middleware('can:solicitud.edit')->name('solicitud.update');
Route::delete('solicitud/{solicitud}', [SolicitudController::class, 'destroy'])->middleware('can:solicitud.delete')->name('solicitud.destroy');
Route::get('solicitud/{solicitud}/aprobar', [SolicitudController::class, 'aprobar'])->middleware('can:jefe-red')->name('solicitud.aprobar');
Route::post('solicitud/rechazar', [SolicitudController::class, 'rechazar'])->middleware('can:jefe-red')->name('solicitud.sol_rechazar');
Route::get('pendientes', [SolicitudController::class, 'reject'])->middleware('can:jefe-red')->name('solicitud.reject');
Route::get('solicitud/{solicitud}/reporte_rechazado', [SolicitudController::class, 'PDF_rechazado'])->middleware('permission:jefe-red|Monitor')->name('solicitud.PDFrechazado');
Route::post('solicitud/{solicitud}/guardar_ampliacion', [SolicitudController::class, 'guardarAmpliacion'])->name('solicitud.guardarAmpliacion');
Route::get('solicitud/{solicitud}/comprobante_solicitud', [SolicitudController::class, 'comprobante_solicitud'])->name('solicitud.comprobante_solicitud');
Route::get('solicitud/{solicitud}/obtener_ampliacion', [SolicitudController::class, 'obtenerAmpliacion'])->name('solicitud.obtenerAmpliaciones');
Route::post('solicitud/solicitud_escaneada', [SolicitudController::class, 'solicitud_escaneada'])->name('solicitud.escaneada');
Route::get('solicitud/{solicitud}/form_rechazar', [SolicitudController::class, 'form_rechazado'])->middleware('can:jefe-red')->name('solicitud.form_rechazado');
Route::get('solicitud/avance', [SolicitudController::class, 'avance'])->name('solicitud.avance');
Route::post('solicitud/pasos_solicitud', [SolicitudController::class, 'pasos_solicitud'])->name('solicitud.pasos_solicitud');
Route::post('solicitud/cambiar_estado', [SolicitudController::class, 'cambiar_estado'])->name('solicitud.cambiar_estado');
Route::get('solicitud/{id}/reporte_historicos', [SolicitudController::class, 'reporte_historicos'])->name('solicitud.reporte_historicos');

// Crud solicitud

// Route::resource('informes', InformeController::class);
Route::get('Informes', [InformeController::class, 'index'])->middleware('can:informes.index')->name('informes.index');
Route::get('Informes/inspeccionados', [InformeController::class, 'inspeccionado'])->name('informes.inspeccionados');
Route::get('Informes/autorizados', [InformeController::class, 'autorizado'])->name('informes.autorizado');
Route::get('Informes/concluidos', [InformeController::class, 'concluido'])->name('informes.concluido');
Route::get('Informes/informes_ejecutados', [InformeController::class, 'informes_ejecutados'])->middleware('can:informes-ejecucion')->name('informes.informes_ejecutados');
Route::get('Informes/registrar_informes', [InformeController::class, 'create'])->middleware('can:informes.create')->name('informes.create');
Route::post('Informes/registrar_informe', [InformeController::class, 'store'])->middleware('can:informes.create')->name('informes.store');
Route::post('Informes/update_costos', [InformeController::class, 'update_costos'])->name('informes.update_costos');
Route::get('Informes/{informe}/edit', [InformeController::class, 'edit'])->middleware('can:informes.edit')->name('informes.edit');
Route::get('Informes/{informe}/show', [InformeController::class, 'show'])->name('informes.show');
Route::get('Informes/{informe}/show_costos', [InformeController::class, 'show_costos'])->name('informes.show_costos');
Route::put('Informes/{informe}', [InformeController::class, 'update'])->middleware('can:informes.edit')->name('informes.update');
Route::get('PDF/{informe}/PDFinforme', [PDFController::class, 'PDF'])->name('descargarPDF.informe');
Route::delete('Informes/{Informe}', [InformeController::class, 'destroy'])->name('informes.destroy');
Route::get('Informes/{informe}/registrar_material', [InformeController::class, 'registrar_material'])->name('informes.registrar_material');
Route::post('Informes/{Informe}/autorizar', [InformeController::class, 'autorizar'])->middleware('can:jefe-red')->name('informes.autorizar');
Route::get('Informes/{informe}/rechazar', [InformeController::class, 'no_autorizar'])->middleware('can:jefe-red')->name('informes.no_autorizar');
Route::get('Informes/{informe}/firmar', [InformeController::class, 'firmar_informe'])->middleware('can:jefe-red')->name('informes.firmar');
Route::get('Informes/{informe}/devolver_asignado', [InformeController::class, 'devolver_asignado'])->middleware('can:jefe-red')->name('informes.devolver_asignado');
Route::get('Informes/{informe}/aprobar_proyecto', [InformeController::class, 'aprobar_proyecto'])->middleware('can:Proyectista')->name('informes.aprobar_proyecto');
Route::post('Informes/{informe}/solicitar_autorizacion', [InformeController::class, 'solicitar_autorizacion'])->middleware('can:informes.edit')->name('informes.solicitar_autorizacion');
Route::post('Informes/esperar_aprobacion', [InformeController::class, 'esperar_aprobacion'])->name('informes.esperar_aprobacion');
Route::post('Informes/reversa_aprobacion', [InformeController::class, 'reversa_aprobacion'])->name('informes.reversa_aprobacion');
Route::post('Informes/verificacion_estado', [InformeController::class, 'verificacion_estado'])->name('informes.verificacion_estado');
Route::get('Informes/ejecutados/{fecha_inicio?}/{fecha_fin?}', [InformeController::class, 'ejecutados'])->name('informes.ejecutados');
// Route::post('Informes/vista_ejecutados', [InformeController::class, 'vista_ejecutados'])->name('informes.vista_ejecutados');
Route::get('Informes/reporte_ejecutados/{fecha_i?}/{fecha_f?}', [InformeController::class, 'reporte_ejecutados'])->name('informes.reporte_ejecutados');
// Modificacion al admin
Route::post('Informes/paso_atras', [InformeController::class, 'paso_atras'])->name('informes.paso_atras');

// CRUD MATERIALES
Route::resource('materials', MaterialController::class)->middleware('can:jefe-red')->names('materials');

// Asigacion de materiales a los informes´
Route::resource('material_informe', Materials_informesController::class)->names('material_informe');
Route::delete('material_informe/{mat_inf}/eliminar', [Materials_informesController::class, 'eliminar_lista'])->name('material_informe.eliminar');

Route::get('PDF/{informe}/PDFpedido', [PDFController::class, 'PDF_pedido'])->name('pedidoPDF.informe');
Route::get('PDF/{informe}/PDFreporte_ampliacion', [PDFController::class, 'PDF_informe_material'])->name('reportePDF.informe_material');
Route::get('PDF/{informe}/PDFreporte_descargo_material', [PDFController::class, 'PDF_informe_descargo_material'])->name('reportePDF.informe_descargo_material');
Route::get('PDF/{id}/acta_final', [PDFController::class, 'acta_final'])->name('reportePDF.acta_final');


// Asigacion de Solicitudes a Inspectores
Route::resource('cronograma', CronogramaController::class)->names('cronograma');
Route::get('Cronograma/registro_cronograma', [CronogramaController::class, 'mostrar'])->name('cronograma.reporte');
Route::get('PDF/{fecha_i?}/{fecha_f?}/{user_id?}/PDFcronograma', [PDFController::class, 'PDF_cronograma'])->name('descargarPDF.cronograma');

//___________________________________DESCARGO DE MATERIALES____________________________________________________________________
Route::resource('descargo', DescargoController::class)->names('descargo'); //Metodo index
// APORTE MATERIAL VECINOS
Route::get('Descargos/{descargo}/{fecha_descargo?}/{valor?}/mostrar_aportes_v', [DescargoController::class, 'mostrar_aportes_v'])->name('descargo.mostrar_aportes_v');
Route::get('Descargos/{descargo}/{fecha_descargo?}/{valor?}/crear_aportes_v', [DescargoController::class, 'crear_aport_v'])->name('descargo.crear_aport_v');
Route::post('Descargos/registrar_aporte_v', [DescargoController::class, 'registrar_aporte_v'])->name('descargo.registrar_aporte_v');
Route::delete('Aporte_eliminar/{descargo}/{fecha_descargo?}/{valor?}', [DescargoController::class, 'eliminar_aporte'])->name('descargo.eliminar_aporte');

app/Models/Material.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Material extends Model
{
    use HasFactory;

    public function informes()
    {
        return $this->belongsToMany('App\Models\Informe','informe_materials','informe_id','material_id');
    }
}

app/Http/Controllers/MaterialController.php
<?php

namespace App\Http\Controllers;

use App\Models\Material;
use Illuminate\Http\Request;
use PhpParser\Node\Expr\Match_;

class MaterialController extends Controller
{

    public function index()
    {
        $materials = Material::all();
        return view('materials.index',compact('materials'));
    }


    public function create()
    {
        return view('materials.create');
    }


    public function store(Request $request)
    {
        $request->validate([
            'nombre_material' => 'required|unique:materials|max:255',
        ]);
        $material = new Material();
        $material->codigo = strtoupper($request->codigo);
        $material->nombre_material = strtoupper($request->nombre_material);
        $material->observaciones = strtoupper($request->observaciones);
        $material->cantidad = intval($request->cantidad);
        $material->precio_unitario = $request->precio_unitario;
        $material->estado = $request->estado;
        $material->unidad_med = strtoupper($request->unidad_medida);
        $material->save();
        return redirect()->route('materials.index');
    }


    public function show($id)
    {
        //
    }


    public function edit(Material $material)
    {
        return view('materials.edit',compact('material'));
    }


    public function update(Request $request, Material $material)
    {
        $material->codigo = strtoupper($request->codigo);
        $material->nombre_material = strtoupper($request->nombre_material);
        $material->observaciones = strtoupper($request->observaciones);
        $material->cantidad = intval($request->cantidad);
        $material->precio_unitario = floatVal($request->precio);
        $material->estado = $request->estado;
        $material->save();
        return redirect()->route('materials.index');
    }

    public function destroy( Material $material)
    {
        // $material->estado = "no disponible";
        $material->delete();
        return redirect()->route('materials.index');
    }

}

resources/views/materials/create.blade.php
@extends('adminlte::page')

@section('title', 'Material')

@section('content_header')
    <h1>Materiales</h1>
@stop

@section('content')
<div class="justify-content-center row">
    <!-- left column -->
    <div class="col-md-8">
    <!-- general form elements -->
        <div class="card card-primary ">
        <div class="card-header">
            <h3 class="card-title">Registrar Material</h3>
        </div>
        <!-- /.card-header -->
        <!-- formulario inicio -->
        <form action="{{route('materials.store')}}" method="POST" class="create" role="form" id="form_materials" autocomplete="off">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="codigo">Codigo del material</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="text" name="codigo" id="codigo" class="form-control" style="text-transform:uppercase;" placeholder="nombre del material" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="nombre_material">Nombre del material</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="text" name="nombre_material" id="nombre_material" class="form-control" style="text-transform:uppercase;" placeholder="nombre del material" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="precio_unitario">Precio Unitario</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="text" name="precio_unitario" id="precio_unitario" class="form-control" placeholder="Precio unitario, use '.' para indicar decimal" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="cantidad">Cantidad</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="text"  name="cantidad" id="cantidad" class="form-control" placeholder="0" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="unidad_medida">Unidad de Medida</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-sort-numeric-down"></i></span>
                        </div>
                        <input type="text" name="unidad_medida" id="unidad_medida" class="form-control" style="text-transform:uppercase;" placeholder="Ej. metros" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="observaciones">Observaciones</label>
                    <div class="input-group ">
                        <textarea name="observaciones" id="observaciones" class="form-control" style="text-transform:uppercase;"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label for="estado">Estado</label>
                    <select class="form-control" name="estado" id="estado">
                        <option value="disponible">Disponible</option>
                        <option value="no disponible">No Disponible</option>
                      </select>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-block btn-primary">Registrar</button>
            </div>
        </form>
        {{-- Fin de formulario --}}
        </div>
    </div>
</div>

@stop

@section('js')
    <script>
    $('.select2').select2();
    const input = document.getElementById('cantidad');
    input.addEventListener('blur', function() {
        const valor = this.value.trim(); // eliminamos los espacios en blanco al inicio y al final
        if (isNaN(valor)) {
            alert('Debe ingresar un número válido.');
            this.value = ''; // borra el valor introducido
        }
    })
    const input2 = document.getElementById('precio_unitario');
    input2.addEventListener('blur', function() {
        const valor = this.value.trim(); // eliminamos los espacios en blanco al inicio y al final
        if (isNaN(valor)) {
            alert('Debe ingresar un número válido.');
            this.value = ''; // borra el valor introducido
        }
    })
    </script>
@stop

resources/views/materials/edit.blade.php
@extends('adminlte::page')

@section('title', 'Editar Material')

@section('content_header')
    <h1>Editar Material</h1>
@stop

@section('content')
<div class="justify-content-center row">
    <!-- left column -->
    <div class="col-md-8">
    <!-- general form elements -->
        <div class="card card-primary ">
        <div class="card-header">
            <h3 class="card-title">Editar Material</h3>
        </div>
        <!-- /.card-header -->
        <!-- formulario inicio -->
        <form action="{{route('materials.update',$material)}}" method="POST" role="form" id="form_materials" autocomplete="off">
            @csrf
            @method('put')
            <div class="card-body">
                <div class="form-group">
                    <label for="codigo">Codigo del material</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="text" name="codigo" id="codigo" class="form-control" style="text-transform:uppercase;" value="{{$material->codigo}}" placeholder="codigo del material">
                    </div>
                </div>
                <div class="form-group">
                    <label for="nombre_material">Nombre del material</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="text" name="nombre_material" id="nombre_material" class="form-control" style="text-transform:uppercase;" value="{{$material->nombre_material}}" placeholder="nombre del material">
                    </div>
                </div>
                <div class="form-group">
                    <label for="cantidad">Cantidad del material</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="number" name="cantidad" id="cantidad" class="form-control"  value="{{$material->cantidad}}" placeholder="cantidad del material">
                    </div>
                </div>
                <div class="form-group">
                    <label for="precio">Precio del material</label>
                    <div class="input-group ">
                        <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-box-open"></i></span>
                        </div>
                        <input type="text" name="precio" id="precio" class="form-control"  value="{{$material->precio_unitario}}" placeholder="precio del material">
                    </div>
                </div>
                <div class="form-group">
                    <label for="observaciones">Observaciones</label>
                    <div class="input-group ">
                        <textarea name="observaciones" id="observaciones" class="form-control" style="text-transform:uppercase;" >{{$material->observaciones}}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="estado">Estado</label>
                    <select class="form-control" name="estado" id="estado">
                        <option value="disponible">Disponible</option>
                        <option value="no disponible">No Disponible</option>
                      </select>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-block btn-primary">Registrar</button>
            </div>
        </form>
        {{-- Fin de formulario --}}
        </div>
    </div>
</div>

@stop

@section('js')
    <script>
    $('.select2').select2();
    const input = document.getElementById('precio');
    input.addEventListener('blur', function() {
        const valor = this.value.trim(); // eliminamos los espacios en blanco al inicio y al final
        if (isNaN(valor)) {
            alert('Debe ingresar un número válido.');
            this.value = ''; // borra el valor introducido
        }
    })
    </script>
@stop

resources/views/materials/index.blade.php
@extends('adminlte::page')

@section('title', 'Material')

@section('content_header')
@stop
@php
    $n=1;
@endphp
@section('content')
    <h1>ELAPAS - MATERIALES
        <a href="{{route('materials.create')}}" class="btn btn-success btn-rounded" style="float: right;">
            Registrar Material <i class="fa fa-plus-square"></i>
        </a>
    </h1>
    <div class="table table-bordered table-hover dataTable table-responsive">
        <table class="table table-bordered datatable" id="example">
        <thead>
          <tr>
            <th>NRO</th>
            <th>CODIGO</th>
            <th>NOMBRE MATERIAL</th>
            <th>CANTIDAD</th>
            <th>PRECIO U.</th>
            <th>OBSERVACION</th>
            <th width="80">ESTADO </th>


            <th>ACCIONES</th>

          </tr>
        </thead>
        <tbody>
            @foreach ($materials as $material)
                <tr>
                    <td>{{$n++}}</td>
                    <td>{{$material->codigo}}</td>
                    <td>{{$material->nombre_material}}</td>
                    <td>{{$material->cantidad}}</td>
                    <td>{{number_format($material->precio_unitario,2)}}</td>
                    <td>{{$material->observaciones}}</td>

                        @if($material->estado=="disponible")
                        <td align="center"><span class="badge badge-success" >{{$material->estado}}</span></td>
                        @else
                        <td align="center"><span class="badge badge-danger" >{{$material->estado}}</span></td>
                        @endif

                    <td>
                        <a href='{{route('materials.edit',$material)}}'
                        class='btn btn-info btn-icon' title="Editar"><i class="fas fa-pencil-alt"></i></a>
                        <form action="{{route('materials.destroy',$material)}}" class="d-inline" method="POST">
                            @csrf
                            @method('delete')
                            <button class='btn btn-danger btn-icon' title="Eliminar" type="submit"><i class="fas fa-trash"></i></button>

                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th>NRO</th>
                <th>CODIGO</th>
                <th>NOMBRE MATERIAL</th>
                <th>CANTIDAD</th>
                <th>PRECIO U.</th>
                <th>OBSERVACION</th>
                <th>ESTADO </th>

                <th>ACCIONES</th>


            </tr>
        </tfoot>
    </table>
</div>

@stop
@section('footer')
<strong>{{date("Y")}} || ELAPAS - SISTEMA DE AMPLIACION DE REDES DE AGUA </strong>
@stop
@section('js')
    <script>
    </script>
@stop